/* main.c generated by valac 0.34.4, the Vala compiler
 * generated from main.vala, do not modify */

/* modules: gtk+-3.0*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>


#define AHM_TYPE_HEADER (ahm_header_get_type ())
#define AHM_HEADER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AHM_TYPE_HEADER, AhmHeader))
#define AHM_HEADER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AHM_TYPE_HEADER, AhmHeaderClass))
#define AHM_IS_HEADER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AHM_TYPE_HEADER))
#define AHM_IS_HEADER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AHM_TYPE_HEADER))
#define AHM_HEADER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AHM_TYPE_HEADER, AhmHeaderClass))

typedef struct _AhmHeader AhmHeader;
typedef struct _AhmHeaderClass AhmHeaderClass;

#define AHM_TYPE_MAIN_WINDOW (ahm_main_window_get_type ())
#define AHM_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AHM_TYPE_MAIN_WINDOW, AhmMainWindow))
#define AHM_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AHM_TYPE_MAIN_WINDOW, AhmMainWindowClass))
#define AHM_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AHM_TYPE_MAIN_WINDOW))
#define AHM_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AHM_TYPE_MAIN_WINDOW))
#define AHM_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AHM_TYPE_MAIN_WINDOW, AhmMainWindowClass))

typedef struct _AhmMainWindow AhmMainWindow;
typedef struct _AhmMainWindowClass AhmMainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _AhmHeaderPrivate AhmHeaderPrivate;
typedef struct _AhmMainWindowPrivate AhmMainWindowPrivate;

struct _AhmHeader {
	GtkHeaderBar parent_instance;
	AhmHeaderPrivate * priv;
};

struct _AhmHeaderClass {
	GtkHeaderBarClass parent_class;
};

struct _AhmMainWindow {
	GtkWindow parent_instance;
	AhmMainWindowPrivate * priv;
};

struct _AhmMainWindowClass {
	GtkWindowClass parent_class;
};


static gpointer ahm_header_parent_class = NULL;
static gpointer ahm_main_window_parent_class = NULL;

gint _vala_main (gchar** args, int args_length1);
GType ahm_header_get_type (void) G_GNUC_CONST;
AhmHeader* ahm_header_new (const gchar* title, const gchar* subtitle);
AhmHeader* ahm_header_construct (GType object_type, const gchar* title, const gchar* subtitle);
AhmMainWindow* ahm_main_window_new (GtkHeaderBar* header, GtkButton* btn);
AhmMainWindow* ahm_main_window_construct (GType object_type, GtkHeaderBar* header, GtkButton* btn);
GType ahm_main_window_get_type (void) G_GNUC_CONST;
enum  {
	AHM_HEADER_DUMMY_PROPERTY
};
enum  {
	AHM_MAIN_WINDOW_DUMMY_PROPERTY
};
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	AhmHeader* header = NULL;
	AhmHeader* _tmp0_ = NULL;
	GtkButton* button = NULL;
	GtkButton* _tmp1_ = NULL;
	AhmMainWindow* _tmp2_ = NULL;
	AhmMainWindow* _tmp3_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = ahm_header_new ("My App", "Made with Vala");
	g_object_ref_sink (_tmp0_);
	header = _tmp0_;
	_tmp1_ = (GtkButton*) gtk_button_new_with_label ("Hello Elementary!");
	g_object_ref_sink (_tmp1_);
	button = _tmp1_;
	_tmp2_ = ahm_main_window_new ((GtkHeaderBar*) header, button);
	g_object_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	_g_object_unref0 (_tmp3_);
	gtk_main ();
	result = 0;
	_g_object_unref0 (button);
	_g_object_unref0 (header);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}


/**
         * Header Constructor
         *
         * @param title string The title to use for the header
         * @param subtitle string The subtitle to use for the header
         */
AhmHeader* ahm_header_construct (GType object_type, const gchar* title, const gchar* subtitle) {
	AhmHeader * self = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (title != NULL, NULL);
	g_return_val_if_fail (subtitle != NULL, NULL);
	self = (AhmHeader*) g_object_new (object_type, NULL);
	_tmp0_ = title;
	gtk_header_bar_set_title ((GtkHeaderBar*) self, _tmp0_);
	_tmp1_ = subtitle;
	gtk_header_bar_set_subtitle ((GtkHeaderBar*) self, _tmp1_);
	gtk_header_bar_set_show_close_button ((GtkHeaderBar*) self, TRUE);
	return self;
}


AhmHeader* ahm_header_new (const gchar* title, const gchar* subtitle) {
	return ahm_header_construct (AHM_TYPE_HEADER, title, subtitle);
}


static void ahm_header_class_init (AhmHeaderClass * klass) {
	ahm_header_parent_class = g_type_class_peek_parent (klass);
}


static void ahm_header_instance_init (AhmHeader * self) {
}


GType ahm_header_get_type (void) {
	static volatile gsize ahm_header_type_id__volatile = 0;
	if (g_once_init_enter (&ahm_header_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AhmHeaderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ahm_header_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AhmHeader), 0, (GInstanceInitFunc) ahm_header_instance_init, NULL };
		GType ahm_header_type_id;
		ahm_header_type_id = g_type_register_static (gtk_header_bar_get_type (), "AhmHeader", &g_define_type_info, 0);
		g_once_init_leave (&ahm_header_type_id__volatile, ahm_header_type_id);
	}
	return ahm_header_type_id__volatile;
}


/**
         * MainWindow Constructor
         *
         * @param header string The title to use for the header
         * @param btn string The subtitle to use for the header
         */
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


AhmMainWindow* ahm_main_window_construct (GType object_type, GtkHeaderBar* header, GtkButton* btn) {
	AhmMainWindow * self = NULL;
	GtkHeaderBar* _tmp0_ = NULL;
	GtkButton* _tmp1_ = NULL;
	g_return_val_if_fail (header != NULL, NULL);
	g_return_val_if_fail (btn != NULL, NULL);
	self = (AhmMainWindow*) g_object_new (object_type, NULL);
	_tmp0_ = header;
	gtk_window_set_titlebar ((GtkWindow*) self, (GtkWidget*) _tmp0_);
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_window_set_default_size ((GtkWindow*) self, 350, 70);
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 10);
	_tmp1_ = btn;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp1_);
	gtk_widget_show_all ((GtkWidget*) self);
	return self;
}


AhmMainWindow* ahm_main_window_new (GtkHeaderBar* header, GtkButton* btn) {
	return ahm_main_window_construct (AHM_TYPE_MAIN_WINDOW, header, btn);
}


static void ahm_main_window_class_init (AhmMainWindowClass * klass) {
	ahm_main_window_parent_class = g_type_class_peek_parent (klass);
}


static void ahm_main_window_instance_init (AhmMainWindow * self) {
}


GType ahm_main_window_get_type (void) {
	static volatile gsize ahm_main_window_type_id__volatile = 0;
	if (g_once_init_enter (&ahm_main_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AhmMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ahm_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AhmMainWindow), 0, (GInstanceInitFunc) ahm_main_window_instance_init, NULL };
		GType ahm_main_window_type_id;
		ahm_main_window_type_id = g_type_register_static (gtk_window_get_type (), "AhmMainWindow", &g_define_type_info, 0);
		g_once_init_leave (&ahm_main_window_type_id__volatile, ahm_main_window_type_id);
	}
	return ahm_main_window_type_id__volatile;
}



